import { Platform } from "react-native";

export const appTheme = {
  colors: {
    background: "#EEF1F7",
    backgroundAlt: "#E4EAF5",
    surface: "#FFFFFF",
    surfaceMuted: "#F7F9FC",
    surfaceTint: "#F4F8FF",
    surfaceTintAlt: "#EEF3FB",
    surfaceTintSoft: "#F2F6FC",
    surfaceBrandSoft: "#E9F7F6",
    surfaceBrandMuted: "#EAF6F8",
    surfaceInfoSoft: "#E8F2FA",
    surfaceInfoMuted: "#EAF2FF",
    surfaceWarningSoft: "#FFF4E9",
    border: "#DDE3EF",
    borderStrong: "#CCD5E6",
    text: "#172033",
    textMuted: "#5C6680",
    textSubtle: "#8690A6",
    primary: "#0E7A8A",
    primaryPressed: "#0A5D69",
    onPrimary: "#F2FCFF",
    accent: "#F59E0B",
    success: "#059669",
    warning: "#B7791F",
    danger: "#CF3348",
    dangerPressed: "#A9382F",
    info: "#2563EB",
    badgeNeutralBg: "#EDF2FA",
    badgeNeutralBorder: "#D9E1EF",
    badgeWarningBg: "#FFF6E9",
    badgeWarningBorder: "#F2D7A8",
    badgeDangerBg: "#FFF0F3",
    badgeDangerBorder: "#F0C2CC",
    badgeSuccessBg: "#E8FBF5",
    badgeSuccessBorder: "#BCE9D9",
    overlay: "rgba(15, 23, 28, 0.45)",
    overlayStrong: "rgba(10, 20, 30, 0.45)",
    backdropOrbA: "#DDE5F4",
    backdropOrbB: "#E8EFFB",
  },
  spacing: {
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 28,
  },
  radius: {
    sm: 14,
    md: 20,
    lg: 28,
    pill: 999,
  },
  fonts: {
    heading: Platform.select({
      ios: "AvenirNext-DemiBold",
      android: "sans-serif-black",
      default: "System",
    }),
    body: Platform.select({
      ios: "AvenirNext-Regular",
      android: "sans-serif",
      default: "System",
    }),
    bodyMedium: Platform.select({
      ios: "AvenirNext-Medium",
      android: "sans-serif-medium",
      default: "System",
    }),
  },
} as const;

export const surfaceShadow = {};
