export type RootStackParamList = {
  Login: undefined;
  ForgotPassword: undefined;
  ResetPassword: { token?: string } | undefined;
  CompanySignup: undefined;
  CompanySetup: undefined;
  ShopSetup: undefined;
  BillingRequired: { reasonCode?: string; message?: string } | undefined;
  SubscriptionSummary: undefined;
  InvitationAccept: { token?: string } | undefined;
  MainTabs: undefined;
  ShopSelector: undefined;
  ShopSelection: undefined;
  BarcodeScanner: {
    mode?: "single" | "auto";
    packId?: string;
    packNumber?: string;
    allowedGameCodes?: string[];
    pendingPacks?: Array<{
      packId?: string;
      packNumber: string;
      label?: string;
    }>;
  };
  PendingSync: undefined;
  SyncConflict: undefined;
};

export type MainStackParamList = {
  BestEntry: undefined;
  OwnerDashboard: undefined;
  MyShifts: undefined;
  MyLeave: undefined;
  MyTimesheet: undefined;
  RotaManage: undefined;
  RotaTimesheet: undefined;
  RotaApprovals: undefined;
  ShiftSwaps: undefined;
  RotaStaffMembers: undefined;
  LeaveManage: undefined;
  LeaveRecord: undefined;
  ShopChecklist: undefined;
  ComplianceChecks: { date?: string } | undefined;
  ComplianceConfig: undefined;
  ComplianceActions: { from?: string; to?: string } | undefined;
  ChecklistConfiguration: undefined;
  ChecklistHistory: undefined;
  Dashboard: undefined;
  UserInvitations: { email?: string; roleId?: string } | undefined;
  UserManagement: undefined;
  ShopConfiguration: undefined;
  ShopFeatureToggles: undefined;
  AppConfiguration: undefined;
  CompanyManagement: undefined;
  ShopManagement: undefined;
  ScratchCardGames: undefined;
  ScratchCardGameCreate: undefined;
  ScratchCardGameEdit: { gameId: string };
  Deliveries: undefined;
  ReceiveDelivery: undefined;
  TemperatureLogs: { date?: string } | undefined;
  TemperatureLogsByDay: undefined;
  TemperatureLogsReport: undefined;
  TemperatureLogsDateRangeReport: undefined;
  TemperatureUnits: undefined;
  TemperatureUnitEdit: { unitId: string };
  TemperatureSchedules: undefined;
  TemperatureScheduleGrid: { from?: string; to?: string } | undefined;
  RefusalRegister: undefined;
  RefusalRegisterByDay: undefined;
  RefusalReport: { from?: string; to?: string } | undefined;
  RefusalManagerReview: undefined;
  RefusalEntryDetails: { entryId: string };
  RefusalEntryEdit: { entryId: string };
  VisitorLog: undefined;
  VisitorLogEntryEdit: { entryId?: string } | undefined;
  VisitorLogReport: { from?: string; to?: string } | undefined;
  ScratchCardPacks: undefined;
  ManualPackCreate: { autoOpenScanner?: boolean } | undefined;
  PackDetails: { packId: string };
  ActivatePack: { packId: string };
  BusinessDay: undefined;
  OpenShift: undefined;
  CloseShift: undefined;
  ShiftDetails: { shiftId: string; shopId: string };
  EnterClosingNumbers: { shiftId: string; shopId: string; shiftName?: string };
  PrizePayout: { shiftId: string };
  SafeDrop: { businessDayId: string; businessDate: string; shopId: string };
  ScratchCardSummary: { businessDayId: string; businessDate: string; shopId: string };
  ShiftReconciliation: { shiftId: string };
  DayEndClose: { businessDayId: string };
  CloseDay: { businessDayId: string; closedShiftCount: number; totalSales: number };
  DailySalesReport: { date?: string } | undefined;
  ShiftSalesReport: undefined;
  ManualClosingReview: undefined;
  StockReport: undefined;
  AuditLog: undefined;
  NotificationLog: undefined;
  Settings: undefined;
  NotificationPreferences: undefined;
  StoreSales: { reportType?: "Shift" | "DayEnd"; shiftId?: string; businessDayId?: string } | undefined;
  TillsConfig: undefined;
  PaymentTypesConfig: undefined;
  TillGroupsConfig: undefined;
  TillLineReport: undefined;
  TillReportReview: { reportId: string };
  TillReportHistory: undefined;
  TillReconciliation: undefined;
  TillPaymentSummary: { businessDayId: string };
};
