export type RootStackParamList = {
  Login: undefined;
  ForgotPassword: undefined;
  ResetPassword: { token?: string } | undefined;
  CompanySignup: undefined;
  CompanySetup: undefined;
  ShopSetup: undefined;
  BillingRequired: { reasonCode?: string; message?: string } | undefined;
  SubscriptionSummary: undefined;
  ChoosePlan: undefined;
  InvitationAccept: { token?: string } | undefined;
  MainTabs: undefined;
  ShopSelector: undefined;
  BarcodeScanner: {
    mode?: "single" | "auto";
    packId?: string;
    packNumber?: string;
    allowedGameCodes?: string[];
    pendingPacks?: Array<{
      packId?: string;
      packNumber: string;
      label?: string;
    }>;
  };
  PendingSync: undefined;
  SyncConflict: undefined;
};

export type MainStackParamList = {
  BestEntry: undefined;
  ShopChecklist: undefined;
  ComplianceChecks: { date?: string } | undefined;
  ComplianceConfig: undefined;
  ComplianceActions: undefined;
  ChecklistConfiguration: undefined;
  ChecklistHistory: undefined;
  Dashboard: undefined;
  UserInvitations: undefined;
  UserManagement: undefined;
  ShopConfiguration: undefined;
  ShopFeatureToggles: undefined;
  AppConfiguration: undefined;
  CompanyManagement: undefined;
  ShopManagement: undefined;
  ScratchCardGames: undefined;
  ScratchCardGameCreate: undefined;
  ScratchCardGameEdit: { gameId: string };
  Deliveries: undefined;
  ReceiveDelivery: undefined;
  TemperatureLogs: { date?: string } | undefined;
  TemperatureLogsByDay: undefined;
  TemperatureLogsReport: undefined;
  TemperatureLogsDateRangeReport: undefined;
  TemperatureUnits: undefined;
  RefusalRegister: undefined;
  RefusalRegisterByDay: undefined;
  RefusalReport: undefined;
  RefusalManagerReview: undefined;
  RefusalEntryDetails: { entryId: string };
  RefusalEntryEdit: { entryId: string };
  ScratchCardPacks: undefined;
  ManualPackCreate: { autoOpenScanner?: boolean } | undefined;
  PackDetails: { packId: string };
  ActivatePack: { packId: string };
  BusinessDay: undefined;
  OpenShift: undefined;
  CloseShift: undefined;
  ShiftDetails: { shiftId: string; shopId: string };
  EnterClosingNumbers: { shiftId: string; shopId: string; shiftName?: string };
  PrizePayout: { shiftId: string };
  SafeDrop: { businessDayId: string; businessDate: string; shopId: string };
  ScratchCardSummary: { businessDayId: string; businessDate: string; shopId: string };
  ShiftReconciliation: { shiftId: string };
  DayEndClose: { businessDayId: string };
  DailySalesReport: { date?: string } | undefined;
  ShiftSalesReport: undefined;
  ManualClosingReview: undefined;
  StockReport: undefined;
  AuditLog: undefined;
  NotificationLog: undefined;
  Settings: undefined;
  NotificationPreferences: undefined;
};
