export type RootStackParamList = {
  Login: undefined;
  CompanySignup: undefined;
  CompanySetup: undefined;
  ShopSetup: undefined;
  BillingRequired: { reasonCode?: string; message?: string } | undefined;
  SubscriptionSummary: undefined;
  ChoosePlan: undefined;
  InvitationAccept: { token?: string } | undefined;
  MainTabs: undefined;
  ShopSelector: undefined;
  BarcodeScanner: { mode?: "single" | "auto"; packId?: string; packNumber?: string };
  PendingSync: undefined;
  SyncConflict: undefined;
};

export type MainStackParamList = {
  BestEntry: undefined;
  Dashboard: undefined;
  UserInvitations: undefined;
  UserManagement: undefined;
  AppConfiguration: undefined;
  CompanyManagement: undefined;
  ShopManagement: undefined;
  ScratchCardGames: undefined;
  ScratchCardGameCreate: undefined;
  ScratchCardGameEdit: { gameId: string };
  Deliveries: undefined;
  ReceiveDelivery: undefined;
  TemperatureLogs: undefined;
  TemperatureLogsByDay: undefined;
  TemperatureLogsReport: undefined;
  TemperatureUnits: undefined;
  RefusalRegister: undefined;
  RefusalRegisterByDay: undefined;
  RefusalReport: undefined;
  RefusalManagerReview: undefined;
  RefusalEntryDetails: { entryId: string };
  RefusalEntryEdit: { entryId: string };
  ScratchCardPacks: undefined;
  ManualPackCreate: { autoOpenScanner?: boolean } | undefined;
  PackDetails: { packId: string };
  ActivatePack: { packId: string };
  BusinessDay: undefined;
  OpenShift: undefined;
  CloseShift: undefined;
  ShiftDetails: { shiftId: string; shopId: string };
  ShiftClose: { shiftId: string; shopId: string };
  PrizePayout: { shiftId: string };
  ShiftReconciliation: { shiftId: string };
  DayEndClose: { businessDayId: string };
  DailySalesReport: undefined;
  ShiftSalesReport: undefined;
  ManualClosingReview: undefined;
  StockReport: undefined;
  AuditLog: undefined;
  NotificationLog: undefined;
  Settings: undefined;
};
